import { DataGridViewModel } from 'app2-common';

export const crmCampaigns: DataGridViewModel = {
  type: 'DataGridView',
  hint: 'Marketing and sales efforts to promote a product or service',
  parent: 'crmBase',
  label: 'Campaigns',
  table: 'crm_campaigns',
  labelField: 'name',
  fields: [
    { name: 'name', label: 'Name', type: 'StringField', hint: 'Name of the campaign', required: true },
    {
      name: 'type',
      label: 'Type',
      type: 'SelectField',
      optionItems: ['email', 'social media', 'print', 'event', 'telemarketing', 'other'],
      hint: 'Type of campaign, used to categorize and track the campaign'
    },
    {
      name: 'status',
      label: 'Status',
      type: 'SelectField',
      optionItems: ['planning', 'active', 'inactive', 'completed'],
      hint: 'Current status of the campaign'
    },
    { name: 'start_date', label: 'Start Date', type: 'DateField', hint: 'Start date of the campaign' },
    { name: 'end_date', label: 'End Date', type: 'DateField', hint: 'End date of the campaign' },
    {
      name: 'budget',
      label: 'Budget',
      type: 'CurrencyField',
      hint: 'Budget allocated for the campaign',
      currency: 'USD'
    },
    {
      name: 'expected_revenue',
      label: 'Expected Revenue',
      type: 'CurrencyField',
      currency: 'USD',
      hint: 'Expected revenue generated by the campaign'
    },
    {
      name: 'actual_cost',
      label: 'Actual Cost',
      type: 'CurrencyField',
      hint: 'Actual cost of the campaign',
      currency: 'USD'
    },
    { name: 'objective', label: 'Objective', type: 'TextField', hint: 'Objective or goal of the campaign' },
    { name: 'description', label: 'Description', type: 'TextField', hint: 'Description of the campaign' },
    {
      name: 'crmLeads',
      type: 'DataGridField',
      relatedView: 'crmLeads',
      relatedField: 'campaign',
      hint: 'Leads generated by the campaign'
    },
    {
      name: 'crmOpportunities',
      type: 'DataGridField',
      relatedView: 'crmOpportunities',
      relatedField: 'campaign',
      hint: 'Opportunities generated by the campaign'
    },
    {
      name: 'crmProducts',
      type: 'DataGridField',
      relatedView: 'crmProducts',
      relatedField: 'campaign',
      hint: 'Products promoted by the campaign'
    }
  ]
};
